language: c
compiler:
    - gcc
    - clang
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ../
    - make install
    - cd ../install/testing
    - ./testscript

